server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
vnpay:
  payment-url: ${VNPAY_PAYMENT_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  tmn-code: ${VNPAY_TMN_CODE}
  secret-key: ${VNPAY_SECRET_KEY}
  return-url: ${VNPAY_RETURN_URL:http://localhost:8080/api/payment/vnpay-return}
  timeout: 30000
