server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/payment_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: YOUR_TMN_CODE
  hash-secret: YOUR_HASH_SECRET
  return-url: http://localhost:3000/payment/return
  timeout: 30000
